version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing project dependencies...
      - npm install
  build:
    commands:
      - echo Initiating build...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
    - build/*
  base-directory: build